 services:
  filebrowser:
    image: 'gtstef/filebrowser'
    environment:
      - FILEBROWSER_CONFIG
      - FILEBROWSER_ADMIN_PASSWORD

    volumes:
      # Main visible folder in Filebrowser
      - type: bind
        source: /data/coolify/applications/ywk444gow0k0sk4skks0gc
        target: /folder
        isDirectory: true

      # Filebrowser internal data
      - type: bind
        source: ./data
        target: /home/filebrowser/data
        isDirectory: true

      # Filebrowser config file
      - type: bind
        source: ./data/config.yaml
        target: /home/filebrowser/data/config.yaml
        isDirectory: false
        content: |
          server:
            sources:
              - path: /folder
                config:
                  defaultEnabled: true
          auth:
            adminUsername: admin
